### PR TITLE
571 issue on GitHub

### PR DESCRIPTION
**Pull request by laritakr**
## Claiming issue 571

@5dced68855d6504d7b4e8ea3cb16970e61178830

relates to #571

$ ./script/start-issue 571

[skip ci]

## Add "request access" button for etd files

@b9717f54cf778570a9d2b301b66e7dbbb1d03964

Text varies according to private, embargo, or institution access rights.
This required a new method in access_renderer to take into account
embargo date combined with viewable by institution.

## Closing issue 571

@7dc2d873d662a2753bf56e57994785928f6d9b00

Closes #571

$ ./script/close-issue 571

### CODE REVIEW

**Comment by jeremyf** [comment]
@laritakr I think the pull request is missing the close issue commit. Can you push your branch again? (The close issue script does not push the branch; though maybe it should).

**Comment by dbrower** [comment]
I think it should be issue dltp-571. (a number without a jira prefix is treated as a GH issue in the start and close scripts).

**Comment by laritakr** [comment]
Oh, yes I think I probably just used 571. That's why I got an odd branch
name. I didn't look at the text on it until now!

I pushed it again.


LaRita Robinson

Senior Ruby on Rails & Digital Library Programmer

Hesburgh Libraries


University of Notre Dame

208 Hesburgh Library

Notre Dame, IN 46556-5677

tel: 574-631-3171

**Comment by jeremyf** [comment]
@laritakr The closing commit is not showing up. Can you double check?

**Pull request merged**
