### PR TITLE
Issue 493

### PR DESCRIPTION
**Pull request by msuhovec**
#493

### CODE REVIEW

**Comment by dbrower** [comment]
Does this need the timestamp file?

**Comment by msuhovec** [comment]
Nope. It invokes the rake task that does.

**Comment by dbrower** [comment]
oh i see. the file is absolute pathed in the code. How do you run it on your development box?

**Comment by jeremyf** [comment]
@dbrower You understand this better. If all is well, please merge.

**Comment by msuhovec** [comment]
There is a JIRA ticket, DLTP-520, for the configurable lastrun file, from the last code inspection on 7/29/16

**Pull request merged**
